<?php

$data = $this->getData('banners');
$mediaURL = $this->getData('mediaURL');
$auto = $this->getData('auto');
$speed = $this->getData('speed');
echo $mediaURL;

?>

<!--<ul class="bxslider">-->
<!--    --><?php
//    $data = $this->getData('banners');
//    $auto = $this->getData('auto') ? "true" : "false";
//    $pager = $this->getData('pager') ? "true" : "false";
//    $speed = intval($this->getData('speed'));
//
//    foreach ($data as $d) {
//        ?>
<!--        <li>-->
<!--            <a href="--><?php //echo $d['link'] ?><!--">-->
<!--                <img src="--><?php //echo $this->getData('mediaURL') . $d['image']; ?><!--"/>-->
<!--            </a>-->
<!--        </li>-->
<!--        --><?php
//    }
//    ?>
<!--</ul>-->
